[general]
live_config_reload = true
ipc_socket = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
dynamic_title = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font",  style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font",  style = "Bold Italic" }
size = 9

[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session"] }
