#            _              
#    _______| |__  _ __ ___ 
#   |_  / __| '_ \| '__/ __|
#  _ / /\__ \ | | | | | (__ 
# (_)___|___/_| |_|_|  \___|
#                           


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

local dotfiles="$HOME/.dotfiles"

export LANG="en_US.UTF-8"
export TERM="xterm-256color"
source "$dotfiles/shell/justinShell"
export GPG_TTY=$TTY

HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=50000
setopt appendhistory extendedglob notify
unsetopt autocd beep nomatch
bindkey -v
bindkey '^R' history-incremental-search-backward
zstyle :compinstall filename '/home/justin/.zshrc'
bindkey '\t' menu-complete

autoload -U compinit
fpath=("$dotfiles/shell/zsh_completions" $fpath)
compinit

# Powerlevel10k theme
powerlevel10k_path="$dotfiles/shell/zsh_plugins/powerlevel10k/powerlevel10k.zsh-theme"
if [[ -f "$powerlevel10k_path" ]]; then
    source $powerlevel10k_path
    POWERLEVEL9K_MODE=nerdfont-complete
    POWERLEVEL9K_ICON_PADDING=moderate
    POWERLEVEL9K_LEGACY_ICON_SPACING=true
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh dir vcs prompt_char)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status virtualenv command_execution_time background_jobs time)
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
    POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=7
    POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=39
    POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=39
    POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=39
    POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND=39
    POWERLEVEL9K_HOME_ICON=''
    POWERLEVEL9K_HOME_SUB_ICON=''
    POWERLEVEL9K_FOLDER_ICON=''
    POWERLEVEL9K_ETC_ICON=''
    POWERLEVEL9K_VCS_BOOKMARK_ICON=''
    # POWERLEVEL9K_VCS_BRANCH_ICON=''
    POWERLEVEL9K_VCS_BRANCH_ICON=''
    POWERLEVEL9K_VCS_COMMIT_ICON=''
    POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
    POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
    POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
    POWERLEVEL9K_VCS_GIT_ICON=''
    POWERLEVEL9K_VCS_HG_ICON=''
    POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=' '
    POWERLEVEL9K_VCS_LOADING_ICON=''
    POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=' '
    POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=''
    POWERLEVEL9K_VCS_STAGED_ICON=''
    POWERLEVEL9K_VCS_STASH_ICON=' '
    POWERLEVEL9K_VCS_SVN_ICON=''
    POWERLEVEL9K_VCS_TAG_ICON=''
    POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION=''
    POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
    POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''
    POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
    POWERLEVEL9K_INSTANT_PROMPT=verbose
    ZLE_RPROMPT_INDENT=0    # Fix extra space after right prompt
fi

# A little bit of Linus madness every day
linus_rants_path="$dotfiles/shell/zsh_plugins/linus-rants/linus-rants.plugin.zsh"
if [[ -f "$linus_rants_path" ]] && \
   $(which shuf > /dev/null) && $(which cowsay > /dev/null) && $(which lolcat > /dev/null); then  # Check dependencies since the plugin doesn't
        source $linus_rants_path
fi

# Enable fuzzy command history and file search
fzf_zsh_path="$dotfiles/shell/zsh_plugins/fzf-zsh-plugin"
if [[ -d "$fzf_zsh_path" ]]; then
    PATH="$PATH:$fzf_zsh_path/bin"
    source "$fzf_zsh_path/fzf-zsh-plugin.plugin.zsh"
fi

# Enable fuzzy tab completion
fzf_tab="$dotfiles/shell/zsh_plugins/fzf-tab/fzf-tab.plugin.zsh"
if [[ -f "$fzf_tab" ]]; then
    source "$fzf_tab"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion



# Show indicator when completion task is running
zmodload zsh/terminfo

function set_completion_indicator {
  echoti sc # save_cursor
  echoti cup $((LINES - 1)) $((COLUMNS - $#1)) # cursor_position
  echoti setaf $2 # set_foreground (color)
  printf %s $1
  echoti sgr 0 # exit_attribute_mode
  echoti rc # restore_cursor
  #sleep 1
}

completion_indicator_text='(completing)'
completion_indicator_color=3
function display_completion_indicator {
  compprefuncs+=(display_completion_indicator)
  set_completion_indicator $completion_indicator_text $completion_indicator_color
}

function hide_completion_indicator {
  comppostfuncs+=(hide_completion_indicator)
  # The completion code erases the indicator, so there's nothing to do.
}

compprefuncs+=(display_completion_indicator)
comppostfuncs+=(hide_completion_indicator)
