#            _              
#    _______| |__  _ __ ___ 
#   |_  / __| '_ \| '__/ __|
#  _ / /\__ \ | | | | | (__ 
# (_)___|___/_| |_|_|  \___|
#                           


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

local dotfiles="$HOME/.dotfiles"

export LANG="en_US.UTF-8"
# export TERM="screen-256color-italic"
source "$dotfiles/shell/justinShell.sh"
export GPG_TTY=$(tty)
eval "$(dircolors ~/.dircolors)"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000
SAVEHIST=50000
setopt appendhistory extendedglob notify
unsetopt autocd beep nomatch
bindkey -v
bindkey '^R' history-incremental-search-backward
zstyle :compinstall filename '/home/justin/.zshrc'
bindkey '\t' menu-complete

autoload -U compinit
fpath=("$dotfiles/shell/zsh_completions" $fpath)
compinit

# Powerlevel10k theme
powerlevel10k_path="$dotfiles/shell/zsh_plugins/powerlevel10k/powerlevel10k.zsh-theme"
if [[ -f "$powerlevel10k_path" ]]; then
  source $dotfiles/shell/p10k.zsh
  initialize_powerlevel10k "$powerlevel10k_path"
fi

# A little bit of Linus madness every day
linus_rants_path="$dotfiles/shell/zsh_plugins/linus-rants/linus-rants.plugin.zsh"
if [[ -f "$linus_rants_path" ]] && \
   $(which shuf > /dev/null) && $(which cowsay > /dev/null) && $(which lolcat > /dev/null); then  # Check dependencies since the plugin doesn't
        source $linus_rants_path
fi

# Enable fuzzy command history and file search
fzf_zsh_path="$dotfiles/shell/zsh_plugins/fzf-zsh-plugin"
if [[ -d "$fzf_zsh_path" ]]; then
    PATH="$PATH:$fzf_zsh_path/bin"
    source "$fzf_zsh_path/fzf-zsh-plugin.plugin.zsh"
fi

# Enable fuzzy tab completion
fzf_tab="$dotfiles/shell/zsh_plugins/fzf-tab/fzf-tab.plugin.zsh"
if [[ -f "$fzf_tab" ]]; then
    source "$fzf_tab"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Show indicator when completion task is running
zmodload zsh/terminfo

function set_completion_indicator {
  echoti sc # save_cursor
  echoti cup $((LINES - 1)) $((COLUMNS - $#1)) # cursor_position
  echoti setaf $2 # set_foreground (color)
  printf %s $1
  echoti sgr 0 # exit_attribute_mode
  echoti rc # restore_cursor
  #sleep 1
}

completion_indicator_text='(completing)'
completion_indicator_color=3
function display_completion_indicator {
  compprefuncs+=(display_completion_indicator)
  set_completion_indicator $completion_indicator_text $completion_indicator_color
}

function hide_completion_indicator {
  comppostfuncs+=(hide_completion_indicator)
  # The completion code erases the indicator, so there's nothing to do.
}

compprefuncs+=(display_completion_indicator)
comppostfuncs+=(hide_completion_indicator)
