---

ghostty_config_dir: "{{
  ansible_facts['env']['HOME'] + '/Library/Application Support/com.mitchellh.ghostty'
  if ansible_facts['os_family'] == 'Darwin'
  else ansible_facts['env']['HOME'] + '/.config/ghostty'
}}"
