---

- name: Deploy dotfiles and related utilities
  hosts: all
  gather_facts: true   # required so ansible_local.dotfiles is loaded for the gating roles
  pre_tasks:
    - name: Ensure dotfiles repository is available
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/ensure_repository.yml"
  roles:
    - toolchain
    - starship
    # Roles are ordered around this role. Roles contributing facts to dotfiles
    # must be before dotfiles_facts. Roles consuming these dotfile facts must
    # be after dotfiles_facts.
    - dotfiles_facts  
    - bash
    - zsh
    - terminfo
    - tmux
    - terminals
    - vim
    - claude
